### ISSUE TITLE
Convenient way of inserting long text blocks in html

### ISSUE THREAD

**Issue by dpashkevich** [jonschlinkert/pre#11]
`p { text: "Lorem ipsum" }` is only useful for short, one-line strings. There needs to be a better syntax for inserting big multiline text blocks. Also,
- The text might contain certain control characters like quotes or curly braces. I don't want to bother escaping them.
- The text might contain characters that need to be transformed to html entities. I don't want to bother doing that either :)

I suggest something like [heredoc](http://en.wikipedia.org/wiki/Here_document) syntax for that:

```
p { 
  text: <<<TXT

Hello dear world!
Lorem "ipsum madness with quotes ' & ampersands madness
pre > html

TXT;
}
```

The text between `<<<TXT` and `TXT;` (the latter is always put in a separate line) receives no processing (so you can put CSS code inside it without having to escape it). You can use an arbitrary keyword instead of `TXT` (so that there can be say a `<<<HELLO` string inside my text and it wouldn't  receive any special processing). It's also a good idea to automatically transform certain characters into their html entities.

The above example would render to the following html:

```
<p>
Hello dear world!
Lorem &quot;ipsum madness with quotes ' &amp; ampersands madness
pre &gt; html
</p>
```

**Comment by jonschlinkert** [comment]
Agreed @dpashkevich, we need to come up with an elegant solution for this.  It would be good to get some discussion going on this before we make a decision on the best way to implement. Keep the ideas coming! and if I come up with anything I'll post it here so we have some options to consider. @doowb any ideas on this?
