### ISSUE TITLE
List of proposed keywords in Pre

### ISSUE THREAD

**Issue by jonschlinkert** [jonschlinkert/pre#16]
Let's get a list going of proposed keywords in Pre. 

doctype-related keywords seem natural candidates. 
- doctype  (selector keyword, gist: https://gist.github.com/3984049)
- xml:lang="en"  (attribute keyword)

**Comment by dpashkevich** [comment]
Mostly stuff that usually appears in the `<head>` section:
- Conditional comments for IE

```
<!--[if IE 6]>
Special instructions for IE 6 here
<![endif]-->
```
- external CSS includes
- external JS includes
- charset `<meta charset='utf-8' />`
- Favicon `<link rel="icon" type="image/x-icon" href="/favicon.ico" />`
- iOS icons `<link rel="apple-touch-icon-precomposed" sizes="57x57" href="apple-touch-icon-114.png" />`
- Search `<link rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" title="MySite" />`
- etc.

Also note that the syntax for the above may be doctype-sensitive (e.g. shorttag syntax). Pre should be smart about this...

**Comment by jonschlinkert** [comment]
I moved the gist I linked above to this wiki so we can both edit it:  https://github.com/sellside/pre/wiki/Pre-Keywords

**Comment by dpashkevich** [comment]
You should fix the link to https://github.com/sellside/pre/wiki/Pre-%22keywords%22 or remove the quotes from the title of the wiki page...

**Comment by jonschlinkert** [comment]
fixed... also, see if you can edit wiki pages too. I think you should be able to, but it would be good to have confirmation on that

**Comment by dpashkevich** [comment]
Yeah, I can edit the wiki. Added my thoughts on "Uncommon Attributes"
