### ISSUE TITLE
Mixin invocation syntax is too similar to nested elements syntax

### ISSUE THREAD

**Issue by dpashkevich** [jonschlinkert/pre#30]
``` sass
.profile {
  .username; // mixin called
}
```

vs

```
.profile {
  .username {}; // child element defined. Difference in only those curly braces
}
```

This is very error prone IMHO.

> @jonschlinkert: in LESS, `.username;` is a mixin and `.username();` is a parametric mixin that can accept variables, operations, etc. as values. To me that makes a lot of sense

Jon, could you explain a bit how it makes sense to you? Why not just always use  `.username();`? Even this little difference would make the syntax clearer. `.username;` looks a lot like you just forgot something. 

As an analogy (which I think is very legit), in most languages you always use parenthesis when calling a function (e.g. `doSomething();`), regardless of whether you pass any arguments or not (or whether the function expects any or not). Mixin in our case is very much like a function that you _call_ (or a partial that you _include_ if you look at it from another perspective, but there is still something you _do_ with it)

**Comment by jonschlinkert** [comment]
We're in agreement on this, let's require () to define and call a mixin. I was going to raise the same question to you and Brian. Initially I only had .mixin(); syntax,  which is how LESS defines parametric mixins, but LESS also uses .mixin; for "regular" mixins. So I tentatively decided to include that syntax until I had a chance to discuss it with you...

For exactly the reasons you've pointed out, I have also felt that mixins are error prone (e.g. human-error) when the function syntax is absent, so I have always used () in LESS regardless of whether or not the mixins are parametric. 

Case closed? :)

**Comment by dpashkevich** [comment]
:+1:
